copy docs to website is also needed

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -135,118 +135,118 @@ jobs:
           token: ${{ secrets.BOT_TOKEN }}
           path: website
 
-      # - name: Copy docs to website
-      #   if: |
-      #     steps.collect-changes.outputs.changesDetectedAfterTag == 'true'
-      #   shell: bash
-      #   run: |
-      #     #!/bin/bash
-      #     CHARTS=(${{ steps.collect-changes.outputs.modifiedChartsAfterTag }})
-      #     echo "Removing Chart Docs prior to regeneration..."
-      #     mkdir -p website/static/img/hotlink-ok/chart-icons || echo "chart-icons path already exists, continuing..."
-      #     for i in "${CHARTS[@]}"
-      #     do
-      #         IFS='/' read -r -a chart_parts <<< "$i"
-      #         if [ -f "charts/${chart_parts[0]}"/"${chart_parts[1]}/Chart.yaml" ]; then
-      #           train=${chart_parts[0]}
-      #           chart=${chart_parts[1]}
-      #           echo "copying docs to website for ${chart}"
-      #           mkdir -p website/docs/charts/${train}/${chart} || echo "chart path already exists, continuing..."
-      #           mkdir -p tmp/website/docs/charts/${train}/${chart}/ || echo "chart path already exists, continuing..."
-      #           if [[ -f "website/docs/charts/${train}/${chart}/CHANGELOG.md" ]]; then
-      #              echo "changelog found..."
-      #              true
-      #           else
-      #              echo "changelog not found, starting with empty changelog..."
-      #              touch "website/docs/charts/${train}/${chart}/CHANGELOG.md"
-      #           fi
+      - name: Copy docs to website
+        if: |
+          steps.collect-changes.outputs.changesDetectedAfterTag == 'true'
+        shell: bash
+        run: |
+          #!/bin/bash
+          CHARTS=(${{ steps.collect-changes.outputs.modifiedChartsAfterTag }})
+          echo "Removing Chart Docs prior to regeneration..."
+          mkdir -p website/static/img/hotlink-ok/chart-icons || echo "chart-icons path already exists, continuing..."
+          for i in "${CHARTS[@]}"
+          do
+              IFS='/' read -r -a chart_parts <<< "$i"
+              if [ -f "charts/${chart_parts[0]}"/"${chart_parts[1]}/Chart.yaml" ]; then
+                train=${chart_parts[0]}
+                chart=${chart_parts[1]}
+                echo "copying docs to website for ${chart}"
+                mkdir -p website/docs/charts/${train}/${chart} || echo "chart path already exists, continuing..."
+                mkdir -p tmp/website/docs/charts/${train}/${chart}/ || echo "chart path already exists, continuing..."
+                if [[ -f "website/docs/charts/${train}/${chart}/CHANGELOG.md" ]]; then
+                   echo "changelog found..."
+                   true
+                else
+                   echo "changelog not found, starting with empty changelog..."
+                   touch "website/docs/charts/${train}/${chart}/CHANGELOG.md"
+                fi
 
-      #           echo "Keeping some docs safe..."
-      #           # keep some docs safe
-      #           mv -f website/docs/charts/${train}/${chart}/CHANGELOG.md tmp/website/docs/charts/${train}/${chart}/CHANGELOG.md || :
+                echo "Keeping some docs safe..."
+                # keep some docs safe
+                mv -f website/docs/charts/${train}/${chart}/CHANGELOG.md tmp/website/docs/charts/${train}/${chart}/CHANGELOG.md || :
 
-      #           echo "Removing old docs and recreating based on charts repo..."
-      #           # remove old docs everywhere and recreate based on charts repo
-      #           rm -rf website/docs/charts/*/${chart} || :
-      #           mkdir -p website/docs/charts/${train}/${chart} || echo "chart path already exists, continuing..."
-      #           yes | cp -rf charts/${train}/${chart}/docs/* website/docs/charts/${train}/${chart}/ 2>/dev/null || :
-      #           yes | cp -rf charts/${train}/${chart}/icon.png website/static/img/hotlink-ok/chart-icons/${chart}.png 2>/dev/null || :
-      #           yes | cp -rf charts/${train}/${chart}/screenshots/* website/static/img/hotlink-ok/chart-screenshots/${chart}/ 2>/dev/null || :
+                echo "Removing old docs and recreating based on charts repo..."
+                # remove old docs everywhere and recreate based on charts repo
+                rm -rf website/docs/charts/*/${chart} || :
+                mkdir -p website/docs/charts/${train}/${chart} || echo "chart path already exists, continuing..."
+                yes | cp -rf charts/${train}/${chart}/docs/* website/docs/charts/${train}/${chart}/ 2>/dev/null || :
+                yes | cp -rf charts/${train}/${chart}/icon.png website/static/img/hotlink-ok/chart-icons/${chart}.png 2>/dev/null || :
+                yes | cp -rf charts/${train}/${chart}/screenshots/* website/static/img/hotlink-ok/chart-screenshots/${chart}/ 2>/dev/null || :
 
-      #           echo "Copying back kept docs..."
-      #           # Copy over kept documents
-      #           mv -f tmp/website/docs/charts/${train}/${chart}/CHANGELOG.md website/docs/charts/${train}/${chart}/CHANGELOG.md 2>/dev/null || :
+                echo "Copying back kept docs..."
+                # Copy over kept documents
+                mv -f tmp/website/docs/charts/${train}/${chart}/CHANGELOG.md website/docs/charts/${train}/${chart}/CHANGELOG.md 2>/dev/null || :
 
-      #           echo "Appending SCALE changelog to actual changelog..."
-      #           # Add SCALE changelog to actual changelog
-      #           # Remove header from changelog
-      #           sed -i '/^---$/,/^---$/d' "website/docs/charts/${train}/${chart}/CHANGELOG.md"
-      #           # Prepend app-changelog to changelog
-      #           cat "charts/${train}/${chart}/app-changelog.md" | cat - "website/docs/charts/${train}/${chart}/CHANGELOG.md" > temp && mv temp "website/docs/charts/${train}/${chart}/CHANGELOG.md"
-      #           echo "Adding changelog header..."
-      #           sed -i '1s/^/---\ntitle: Changelog\n---\n\n/' "website/docs/charts/${train}/${chart}/CHANGELOG.md" || echo "failed to add changelog header..."
+                echo "Appending SCALE changelog to actual changelog..."
+                # Add SCALE changelog to actual changelog
+                # Remove header from changelog
+                sed -i '/^---$/,/^---$/d' "website/docs/charts/${train}/${chart}/CHANGELOG.md"
+                # Prepend app-changelog to changelog
+                cat "charts/${train}/${chart}/app-changelog.md" | cat - "website/docs/charts/${train}/${chart}/CHANGELOG.md" > temp && mv temp "website/docs/charts/${train}/${chart}/CHANGELOG.md"
+                echo "Adding changelog header..."
+                sed -i '1s/^/---\ntitle: Changelog\n---\n\n/' "website/docs/charts/${train}/${chart}/CHANGELOG.md" || echo "failed to add changelog header..."
 
-      #           echo "Creating index.md..."
-      #           touch website/docs/charts/${train}/${chart}/index.md
-      #           (
-      #             echo "---"
-      #             echo "title: ${chart}"
-      #             echo "---"
-      #           ) >> website/docs/charts/${train}/${chart}/index.md
-      #           echo "" >> website/docs/charts/${train}/${chart}/index.md
-      #           version=$(cat charts/${train}/${chart}/Chart.yaml | grep "^version: " | awk -F" " '{ print $2 }')
-      #           appversion=$(cat charts/${train}/${chart}/Chart.yaml | grep "^appVersion: " | awk -F" " '{ print $2 }')
-      #           echo '![Version: '"${version}"'](https://img.shields.io/badge/Version-'"${version}"'-informational?style=flat-square) ![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square) ![AppVersion: '"${appversion}"'](https://img.shields.io/badge/AppVersion-'"${appversion}"'-informational?style=flat-square)' >> website/docs/charts/${train}/${chart}/index.md
-      #           echo "" >> website/docs/charts/${train}/${chart}/index.md
-      #           cat charts/${train}/${chart}/Chart.yaml | yq .description -r >> website/docs/charts/${train}/${chart}/index.md
-      #           echo "" >> website/docs/charts/${train}/${chart}/index.md
-      #           echo "## Chart Sources" >> website/docs/charts/${train}/${chart}/index.md
-      #           echo "" >> website/docs/charts/${train}/${chart}/index.md
-      #           cat charts/${train}/${chart}/Chart.yaml | go-yq .sources -r >> website/docs/charts/${train}/${chart}/index.md
-      #           echo "" >> website/docs/charts/${train}/${chart}/index.md
-      #           echo "## Available Documentation" >> website/docs/charts/${train}/${chart}/index.md
-      #           echo "" >> website/docs/charts/${train}/${chart}/index.md
+                echo "Creating index.md..."
+                touch website/docs/charts/${train}/${chart}/index.md
+                (
+                  echo "---"
+                  echo "title: ${chart}"
+                  echo "---"
+                ) >> website/docs/charts/${train}/${chart}/index.md
+                echo "" >> website/docs/charts/${train}/${chart}/index.md
+                version=$(cat charts/${train}/${chart}/Chart.yaml | grep "^version: " | awk -F" " '{ print $2 }')
+                appversion=$(cat charts/${train}/${chart}/Chart.yaml | grep "^appVersion: " | awk -F" " '{ print $2 }')
+                echo '![Version: '"${version}"'](https://img.shields.io/badge/Version-'"${version}"'-informational?style=flat-square) ![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square) ![AppVersion: '"${appversion}"'](https://img.shields.io/badge/AppVersion-'"${appversion}"'-informational?style=flat-square)' >> website/docs/charts/${train}/${chart}/index.md
+                echo "" >> website/docs/charts/${train}/${chart}/index.md
+                cat charts/${train}/${chart}/Chart.yaml | yq .description -r >> website/docs/charts/${train}/${chart}/index.md
+                echo "" >> website/docs/charts/${train}/${chart}/index.md
+                echo "## Chart Sources" >> website/docs/charts/${train}/${chart}/index.md
+                echo "" >> website/docs/charts/${train}/${chart}/index.md
+                cat charts/${train}/${chart}/Chart.yaml | go-yq .sources -r >> website/docs/charts/${train}/${chart}/index.md
+                echo "" >> website/docs/charts/${train}/${chart}/index.md
+                echo "## Available Documentation" >> website/docs/charts/${train}/${chart}/index.md
+                echo "" >> website/docs/charts/${train}/${chart}/index.md
 
-      #           echo "Iterating over all files in the docs directory..."
-      #           # Iterate over all files in the docs directory
-      #           for file in website/docs/charts/${train}/${chart}/*.md; do
-      #             # Extract the file name and first line from each file
-      #             filename=$(basename "${file}")
-      #             echo "Found doc file: ${file}"
-      #             ok_title="false"
-      #             echo "Getting the first line"
-      #             h=$(head -n 1 "${file}")
-      #             echo "The first line is: ${h}. Checking validity..."
-      #             # Check if the first line has ---
-      #             if [[ "${h}" == "---" ]]; then
-      #               echo "First line is ---, continuing..."
-      #               ok_title="true"
-      #             elif [[ "${h}" == "# "* ]]; then
-      #               echo "First line is #..."
-      #               ok_title="false"
-      #             fi
-      #             if [ ${ok_title} == "false" ]; then
-      #               echo "Doc title should use front matter and not # for title, for example"
-      #               echo "---"
-      #               echo "title: some title"
-      #               echo "---"
-      #             else
-      #               echo "Not bad title found, continuing..."
-      #               title=$(cat "${file}" | grep "title: " | sed 's/title: //' | head -n 1)
-      #               echo "The title is: ${title}"
-      #               # Create a markdown link using the file name and title
-      #               link="[**${title}**](./${filename})"
-      #               echo "The link is: ${link}"
-      #               if [ ${filename} != "index.md" ]; then
-      #                 # Append the link to the index.md file
-      #                 echo "- ${link}" >> website/docs/charts/${train}/${chart}/index.md
-      #               fi
-      #             fi
-      #           done
+                echo "Iterating over all files in the docs directory..."
+                # Iterate over all files in the docs directory
+                for file in website/docs/charts/${train}/${chart}/*.md; do
+                  # Extract the file name and first line from each file
+                  filename=$(basename "${file}")
+                  echo "Found doc file: ${file}"
+                  ok_title="false"
+                  echo "Getting the first line"
+                  h=$(head -n 1 "${file}")
+                  echo "The first line is: ${h}. Checking validity..."
+                  # Check if the first line has ---
+                  if [[ "${h}" == "---" ]]; then
+                    echo "First line is ---, continuing..."
+                    ok_title="true"
+                  elif [[ "${h}" == "# "* ]]; then
+                    echo "First line is #..."
+                    ok_title="false"
+                  fi
+                  if [ ${ok_title} == "false" ]; then
+                    echo "Doc title should use front matter and not # for title, for example"
+                    echo "---"
+                    echo "title: some title"
+                    echo "---"
+                  else
+                    echo "Not bad title found, continuing..."
+                    title=$(cat "${file}" | grep "title: " | sed 's/title: //' | head -n 1)
+                    echo "The title is: ${title}"
+                    # Create a markdown link using the file name and title
+                    link="[**${title}**](./${filename})"
+                    echo "The link is: ${link}"
+                    if [ ${filename} != "index.md" ]; then
+                      # Append the link to the index.md file
+                      echo "- ${link}" >> website/docs/charts/${train}/${chart}/index.md
+                    fi
+                  fi
+                done
 
-      #           rm -rf temp || :
-      #         fi
-      #     done
+                rm -rf temp || :
+              fi
+          done
 
       # - name: Commit Website Changes
       #   if: |
